### ISSUE TITLE
Restore the copyrights you erased for other people's code that you are using

### ISSUE THREAD

**Issue by pkelsey** [F-Stack/f-stack#2]
IANAL, but this is plainly silly.  Moving/renaming files, renaming symbols, deleting some lines - none of these things remove the original copyright of the code you are still using from https://github.com/pkelsey/libuinet (and the code that libuinet used from elsewhere without erasing the original copyright).  For a quick and easy example, compare the functions in ff_host_interface.c to the corresponding ones in uinet_host_interface.c.

While it's nice to see another public take on a userland FreeBSD stack, this one with dpdk integration for packets dpdk and a microthreads/compat sockets interface, calling the work "independently developed" in the README when you are clearly relying on (directly using) the work of others, is a bad approach.

**Comment by whl739** [comment]
Sorry.We'll add it as soon as possible.

**Comment by jfb8856606** [comment]
We refer to a number of projects, but forget to add libuinet's copyright, sorry for it.

The "independently developed" in README means the first TCP/IP stack version of F-Stack in 2012,  it is no longer being maintained, and doesn't open source.  Now we use FreeBSD as TCP/IP stack instead of it，and copy it to userspace referred to libuinet and kmm-sandbox.

**Comment by whl739** [comment]
@pkelsey 
We have added libplebnet and libuinet's copyrights in README, LICENSE and some source files.

**Comment by pkelsey** [comment]
Thank you.
