### ISSUE TITLE
Locks in freebsd code

### ISSUE THREAD

**Issue by anandhkrishnan** [F-Stack/f-stack#201]
Hello,

I happened to see your presentation in a DPDK event (online). It says there are no locks. Did you guys remove the locks (in the original code) or you say that only because each process works on its own copy. Also, what do you think will need to make it work in a multi threading environment?

Thanks

**Comment by whl739** [comment]
For example, see lib/include/mutex.h, we use `undef` to remove the original lock macros, and define these macros to make them do nothing. And see lib/include/ff_lock.c, we compile this instead of the orginal kern_lock.c.

>  what do you think will need to make it work in a multi threading environment?

If you want to work in multi-thread architecture, to work with independent network stack for every thread, there will be more changes to the FreeBSD source codes, for example, we have to change all the global variables to thread local variables.
