### ISSUE TITLE
F-stack Memory 

### ISSUE THREAD

**Issue by chavalev** [F-Stack/f-stack#218]
Regarding the memory that should supply allocation for all necessary freeBSD stack structures , like socket, inpcb, tcpcb etc' :
1. Isn;' t the amount of memory that is supplied in ff_freebsd_init is too small to hold 10 million concurrent connections ( like is described in development guide ) ?
2. Since everything is now in user mode , wouldn't it be better to convert all the above allocations to DPDK memory pool , by using rte_mempool_create to create the pool and rte_mempool_get to get an object when the structure is created ( and obviously rte_mempool_put to return to the pool when connection is terminated ) ?
It consumes more memory ( as you need to allocate fix size pool) , but looks more efficient and simple 
[ Excluding the mbuf part now ]

**Comment by whl739** [comment]
1. The memory in `ff_freebsd_init` is only used for initialization.  When the memory is not enough, it will be allocated by `kern_malloc`(mmap enough pages) and `malloc`(just malloc by libc).
2. We didn't replace libc's `malloc` with `rte_mempool` or `rte_malloc`, because in freebsd stack, there are lots of memory malloced with flag `WAITOK`, this flag means that the memory must be allocated successful anyway, and it won't be checked if it is NULL. So if we use the memory of huge pages, there may be crashed.
But even though, we have a plan to use the `rte_mempool` or `rte_malloc` in the future, and try to resolve it.

**Comment by chavalev** [comment]
The idea in using rte_mempool is that all your required allocation is done in init time .  During "work time" , i.e.  when TCP / UDP connections are created , they only get an object from a pool that was already allocated , hence no allocation on-the-fly . Again , the con is that you need to pre-allocate a fixed number of objects , i.e. , to know what are your system  max capacity ( for example , concurrent 1M connections ) .

**Comment by whl739** [comment]
Yes, you are right, but it is not so simple, and there will be more changes to freebsd's source code.
