### ISSUE TITLE
Some issues of current version FreeBSD

### ISSUE THREAD

**Issue by zouyonghao** [F-Stack/f-stack#555]
I recently tested f-stack and found some issues that are in FreeBSD source, I reported some bugs [here](https://bugs.freebsd.org/bugzilla/buglist.cgi?bug_status=New&bug_status=Open&bug_status=In%20Progress&bug_status=UNCONFIRMED&email1=yonghaoz1994%40gmail.com&emailreporter1=1&emailtype1=equals&list_id=383600&query_format=advanced&resolution=---) .

Maybe f-stack should sync the FreeBSD source after these bugs get fixed.

**Comment by jfb8856606** [comment]
Thanks for your feedback, we will upgrade to FreeBSD release/releng 13 next year, to support BBR.

Before that, if there is some serious bugs fix, we will consider sync them.

**Comment by kmacy** [comment]
@jfb8856606  FYI, you're going to have to adapt `epoch(9)` ( https://github.com/freebsd/freebsd-src/blob/main/sys/kern/subr_epoch.c ) to work in user space. Instead of a per-cpu record you'll need a per thread record. With luck you will find it straightforward. Others have not found that to be the case.

**Comment by jfb8856606** [comment]
F-Stack has support FreeBSD-13.0, close this issue.
