### ISSUE TITLE
Q: Why net.inet.udp.maxdgram is not supported by config.ini, and cannot be changed by ff_sysctl?

### ISSUE THREAD

**Issue by phong-zhu** [F-Stack/f-stack#572]
I am using UDP in micro thread of F-Stack. I found that net.inet.udp.maxdgram is 9216 by command 'ff_sysctl -a'. I tried two ways to change this value. First, add one line in config.ini, but when runing application, it told me that 'kernel_sysctlbyname failed: net.inet.udp.maxdgram=16384, error:22'. Second, I tried to use 'ff_sysctl -w', though 'ff_sysctl -a' showed the value had been changed, the app still not worked(returned Message too long(90)).

So, do we have any way to change net.inet.udp.maxdgram? Hope your answer. Thanks.

**Comment by freak82** [comment]
I think the setting via the config file fails because of the following reasons:
1. This option is defined in `freebsd/netinet/udp_usrreq.c` as
```
SYSCTL_ULONG(_net_inet_udp, UDPCTL_MAXDGRAM, maxdgram, CTLFLAG_RW,              
    &udp_sendspace, 0, "Maximum outgoing UDP datagram size");
```
So the option expects `unsigned long` value which is 8 bytes in size.
2. The F-stack does in `lib/ff_config.c` the following
```
} else if (strcmp(section, "sysctl") == 0) {
        cur = &cfg->freebsd.sysctl;

        if (is_integer(value)) {
            if (strcmp(name, "kern.ipc.maxsockbuf") == 0) {
                long *p = (long *)malloc(sizeof(long));
                *p = atol(value);
                newconf->value = (void *)p;
                newconf->vlen = sizeof(*p);
            } else {
                 int *p = (int *)malloc(sizeof(int));
                 *p = atoi(value);
                 newconf->value = (void *)p;
                 newconf->vlen = sizeof(*p);
            }
        } else {
            newconf->value = (void *)newconf->str;
            newconf->vlen = strlen(value);
        }
} else {
 ```
You may see that except for `kern.ipc.maxsockbuf` it represents all other options as integers which are 4 bytes in size.
You may try to add your condition here. Something like
```
        ...
         if (strcmp(name, "kern.ipc.maxsockbuf") == 0 || strcmp(name, "net.inet.udp.maxdgram") == 0) {
         ...
 ```
 and check if this works as a workaround.

**Comment by phong-zhu** [comment]
I've tried the answer. It works very well. Learned a lot! Thank you.
