### ISSUE TITLE
Use f-stack with another packet I/O framework?

### ISSUE THREAD

**Issue by thegreathir** [F-Stack/f-stack#589]
Can we use f-stack with another packet I/O framework (like netmap) rather than DPDK?
If yes how and if no is it in your plans to take apart f-stack and DPDK so everyone can use it with any packet I/O framework?

**Comment by kmacy** [comment]
I doubt Tencent can make the business case to resource that internally since the DPDK is what they're (presumably) using in production. I would take a look at the immediate predecessor to f-stack, libuinet, https://github.com/pkelsey/libuinet which did support netmap. It probably isn't that difficult to update that to work with the newer f-stack. I'll probably end up settling on DPDK for my application so don't see an immediate need for this.

**Comment by jfb8856606** [comment]
Yes, F-Stack uses DPDK because we use DPDK extensively in production, so maybe you will support netmap in F-Stack by yourself, if you need it.
