### ISSUE TITLE
Pcap timestamp issue

### ISSUE THREAD

**Issue by daneshzg** [F-Stack/f-stack#592]
Hey guys,
Is it possible to have more timestamp accuracy (nanoseconds) in .pcap trace file of the f-stack? Currently, I receive the same timestamp for many packets.
Your support is really appreciated

![image](https://user-images.githubusercontent.com/78939253/113848463-c8864d00-9798-11eb-96f8-3bdd855f0202.png)

**Comment by daneshzg** [comment]
Is it possible to have hz > 1000 ?

**Comment by freak82** [comment]
Hi there,

I'm not from the team behind F-stack but I'll try to explain what probably happens and what could be done in my opinion.
1. The F-stack reads and writes packets to the NIC queues in bursts i.e. it tries to read and write up to N packets at once. As far as I remember the N is set to 32 in the F-stack code. However, it can read/write even single packet in some cases depending on the traffic. It reads and writes packets in bursts/groups because it's more effective in this way instead of reading packet by packet.
2. If we look at the code where packets are read from the NIC queues, we can see that after a group of packet is read it's written packet by packet to the pcap file via the `ff_dump_packets` function which resides in `lib/ff_dpdk_pcap.c`. The logic is similar for the send side where the packets are collected for some time in group before being queued to the NIC queue.
3. Inside this function a timestamp with microsecond precision is set for every packet with the following code
```
    gettimeofday(&ts, NULL);
    pcap_hdr.sec = ts.tv_sec;
    pcap_hdr.usec = ts.tv_usec;
```
I suspect that by some reason the `gettimeofday` returns the same timestamp values for every packet from given burst. Some articles in internet point to cases where `gettimeofday` may not have microsecond accuracy.

What can be tried to have better precision here:
- The timestamp can be get once with `gettimeofday` for the whole burst and the adjusted for every packet using `rte_rdtsc` and `rte_get_tsc_hz`. The DPDK functions will be used to measure the microseconds passed for logging each packet and this time will be added to the initial time returned by `gettimeofday` and the values will be logged for each packet. Disadvantage of this solution is that it'll require some redesign of the API for logging the packets in a pcap file.
- Another possible solution is to increase the accuracy of the timestamp to nanoseconds. This need to be advertised in the global pcap hader as shown [here](https://wiki.wireshark.org/Development/LibpcapFileFormat#line-39). The change will be done in `ff_enable_pcap` specifically this line `pcap_file_hdr.magic = 0xA1B2C3D4;`. Then for the actual timestamping the `gettimeofday` will be replaced by `clock_gettime(CLOCK_REALTIME, ...)`. The disadvantage of this solution is that the older versions of libpcap won't be able to read the file as pointed [here](https://wiki.wireshark.org/Development/LibpcapFileFormat#line-20).

These are my ideas what you can try about this issue. The second one is easy to be added because it will simply change 3-4 lines of code. I'm not 100% sure if it'll help though. The `clockgettime` may also return the same timestamps by the same reason the `gettimeofday` returns them. You can try it, if you want. I would try it myself but don't have time currently. I'm curious about the results though :).

**Comment by jfb8856606** [comment]
Thanks @freak82 .

And you can try modify `pkt_tx_delay=100` to `pkt_tx_delay=0`, F-Stack will send the packet immediately, not to wait for 32 packets or 100us.

**Comment by daneshzg** [comment]
@freak82 Thank you, I'll give it a try.
@jfb8856606 I did the `pkt_tx_delay=0` and it did not have any affect on .pcap time stamps

**Comment by daneshzg** [comment]
@freak82 `gettimeofday` works for `pcap` and SIFTR log.
Thank you
