### ISSUE TITLE
Too high default value for the `freebsd.physmem` config varaible

### ISSUE THREAD

**Issue by freak82** [F-Stack/f-stack#608]
The default value assigned to this variable in `ff_default_config` function is `cfg->freebsd.physmem = 1048576*256;`.
However, this value seems to be too high because the `physmem` variable seems to be used to set the available physical memory in pages, not in bytes.
For example, it's passed to `init_param2(physmem);` in `ff_init_main.c` and the signature of the function is `void init_param2(long physpages);` in `freebsd/sys/systm.h`.
Also, in `freebsd/kern/kern_mbuf.c` the `physmem` variable is used to calculate the real memory in bytes - `realmem = (quad_t)physmem * PAGE_SIZE;` in `static void tunable_mbinit(void *dummy)`.

**Comment by jfb8856606** [comment]
Yes, it means the num of pages and default is 1 TB memory in bytes, because the default value of some other parameters are very high.

Now, you can set `physmem` parameters in `config.ini`'s `[freebsd.boot]` section to modify it, we will consider adjusting the default values of each parameter later.

**Comment by freak82** [comment]
I see. Thanks for the explanation.
