### ISSUE TITLE
dev or master repo?

### ISSUE THREAD

**Issue by dkuo123** [F-Stack/f-stack#685]
I saw you have both dev and master repo, which one should I download and use?
some of the tools isn't in dev branch, such as dpdk-setup.sh, is it intentional? do they use different DPDK version? any plan to make it working on the current stable version(dpdk-21.11.1)?
Also, most importantly, if the readme on how to build the package for master, or dev?

**Comment by jfb8856606** [comment]
Yes, they use different DPDK version, since DPDK 20.11(LTS), the script `dpdk-setup.sh` has been remvoed by DPDK, and only use meson and ninja to compile DPDK.

Master or Dev branch's README.md match its own DPDK version, follow it.

And now master branch use DPDK 20.11.6(LTS), dev branch use DPDK 21.11.2(LTS), can be used for comparative testing of applications， but if you need to use it in a more important online environment, you can choose release F-Stack-1.21.2 with branch 1.21(LTS)  now（2022.09),   that use DPDK 19.11.13(LTS).
