### ISSUE TITLE
Why the default optimization level of f-stack is O0?

### ISSUE THREAD

**Issue by renzibei** [F-Stack/f-stack#711]
Will there be any bugs if using higher optimization level?

**Comment by hailongeric** [comment]
I don't meet the error with O2.

**Comment by renzibei** [comment]
Are you sure that you are setting the optimization level of dpdk library instead of the application code? When I change the optimization level in libs/Makefile, there would be crashes.

**Comment by hailongeric** [comment]
Sorry, I can't meet any error in running. But I meet many errors in the compiler procedure.  I change some compiler's options and some src code. And make it compile successfully.

**Comment by renzibei** [comment]
I also encounter compiiler errors and need to change the codes when using O2. By the way, did you comment out "FF_INET6=1"? Could you kindly share one fork of the f-stack codes with O2 enabled? Thanks!

**Comment by renzibei** [comment]
After some changes to the sources of f-stack, currently I can also avoid errors in runtime.

**Comment by jfb8856606** [comment]
Because  release 1.22 and after not stable enough now, may need frequent debugging，so enable -O0 by default. And it's enable -O2 by default in release 1.21(LTS).When the latest version is stable, it will be modified to -O2 by default.

You can comment out this line in `lib/Makefile` to enable -O2, and hte performance will be greatly improved.
`DEBUG=-O0 -gdwarf-2 -g3 -Wno-format-truncation`
