### ISSUE TITLE
The network latency of test example is worse than Linux kernel socket

### ISSUE THREAD

**Issue by beef9999** [F-Stack/f-stack#765]
@jfb8856606 你好，我将某个tcp流量应用了rte flow规则，转发到另一个VF给f-stack用，发现网络延迟增加了约一倍。请问这符合预期吗？

Linux内核延迟：40微秒
f-stack延迟：99微秒
环境：25G网卡 
测试程序：example/main.c
版本：1.22

-------

Hi, I applied the rte flow rule to a certain tcp traffic and forwarded it to another VF for f-stack, and found that the network delay has doubled. Is this as expected?

Linux kernel latency: 40 us
f-stack latency: 99 us
Environment: 25Gb Mellanox NIC
Test program: example/main.c
Version: 1.22

**Comment by jfb8856606** [comment]
Hi 你好，

F-Stack‘s The default parameters are for high concurrency, if you want to test the latency of a single connection, you need modify some parameters’ value, Including but not limited to the following parameters
```
idle_sleep=0
pkt_tx_delay=100
net.inet.tcp.delayed_ack=0
```
Under normal circumstances, it is not recommended to modify the default values of these parameters, unless there are special needs.

发件人: Bob Chen ***@***.***>
发送时间: 2023年4月26日 15:17
收件人: F-Stack/f-stack ***@***.***>
抄送: fengbojiang(姜凤波) ***@***.***>; Mention ***@***.***>
主题: [Internet][F-Stack/f-stack] [Flow Director/Bifurcation] Will rte flow rules increase packet latency? (Issue #765)


@jfb8856606<https://github.com/jfb8856606> 你好，我将某个tcp流量应用了rte flow规则，转发到另一个VF给f-stack用，发现网络延迟增加了约一倍。请问这符合预期吗？

Linux内核延迟：40微秒
f-stack延迟：99微秒
环境：25G网卡
测试程序：example/main.c
版本：1.22

________________________________

Hi, I applied the rte flow rule to a certain tcp traffic and forwarded it to another VF for f-stack, and found that the network delay has doubled. Is this as expected?

Linux kernel latency: 40 us
f-stack latency: 99 us
Environment: 25Gb Mellanox NIC
Test program: example/main.c
Version: 1.22

**Comment by jfb8856606** [comment]
pkt_tx_delay=0

发件人: fengbojiang(姜凤波)
发送时间: 2023年4月27日 11:12
收件人: 'F-Stack/f-stack' ***@***.***>; F-Stack/f-stack ***@***.***>
抄送: Mention ***@***.***>
主题: 回复: [Internet][F-Stack/f-stack] [Flow Director/Bifurcation] Will rte flow rules increase packet latency? (Issue #765)

Hi 你好，

F-Stack‘s The default parameters are for high concurrency, if you want to test the latency of a single connection, you need modify some parameters’ value, Including but not limited to the following parameters
```
idle_sleep=0
pkt_tx_delay=100
net.inet.tcp.delayed_ack=0
```
Under normal circumstances, it is not recommended to modify the default values of these parameters, unless there are special needs.

发件人: Bob Chen ***@***.******@***.***>>
发送时间: 2023年4月26日 15:17
收件人: F-Stack/f-stack ***@***.******@***.***>>
抄送: fengbojiang(姜凤波) ***@***.******@***.***>>; Mention ***@***.******@***.***>>
主题: [Internet][F-Stack/f-stack] [Flow Director/Bifurcation] Will rte flow rules increase packet latency? (Issue #765)


@jfb8856606<https://github.com/jfb8856606> 你好，我将某个tcp流量应用了rte flow规则，转发到另一个VF给f-stack用，发现网络延迟增加了约一倍。请问这符合预期吗？

Linux内核延迟：40微秒
f-stack延迟：99微秒
环境：25G网卡
测试程序：example/main.c
版本：1.22

________________________________

Hi, I applied the rte flow rule to a certain tcp traffic and forwarded it to another VF for f-stack, and found that the network delay has doubled. Is this as expected?

Linux kernel latency: 40 us
f-stack latency: 99 us
Environment: 25Gb Mellanox NIC
Test program: example/main.c
Version: 1.22

**Comment by beef9999** [comment]
After setting these configs, the latency went back to normal.

**Comment by beef9999** [comment]
@jfb8856606 

The original option of `pkt_tx_delay=100` is really poisoned. It almost decreased 70% of the total bandwidth.

Besides, the default Makefile was somehow using the DEBUG build mode...

The final performance comparison is as below:

**512 Bytes TCP echo server throughput**



|            Server socket type             | Client traffic type (ping-pong) | Client traffic type (stream) |
|:-----------------------------------------:|:-------------------------------:|:----------------------------:| 
|  Linux 6.x kernel + io_uring + coroutine  |            1.03Gb/s             |           2.60Gb/s           |
| f-stack (FreeBSD + DPDK) + async-callback |            1.23Gb/s             |           3.74Gb/s           |

We are trying to combine f-stack and coroutine together, so users can write more flexible code (not like the current async stype). In this situation, the latter one might drop a little bit, considering there might be the context switch overhead.

Anyway it looks like a promising results.

**Comment by jfb8856606** [comment]
The 1.22 release tag default build as DEBUG for debug, because it is not stable, you can disable DEBUG by modifying the `#DEBUG=-O0 -gdwarf-2 -g3 -Wno-format-truncation` in `lib/Makefile`, the performance will be greatly improved.

And the last code in dev branch, DEBUG is disabled by default.

发件人: Bob Chen ***@***.***>
发送时间: 2023年4月27日 17:07
收件人: F-Stack/f-stack ***@***.***>
抄送: fengbojiang(姜凤波) ***@***.***>; Mention ***@***.***>
主题: [Internet]Re: [F-Stack/f-stack] The network latency of test example is worse than Linux kernel socket (Issue #765)


@jfb8856606<https://github.com/jfb8856606>

The original option of pkt_tx_delay=100 is really poisoned. It almost decreased 70% of the total bandwidth.

Besides, the default Makefile was somehow using the DEBUG build mode...

The final performance comparison is as below:

512 Bytes TCP echo server throughput
Server socket type

Client traffic type (ping-pong)

Client traffic type (stream)

Linux 6.x kernel + io_uring + coroutine

1.03Gb/s

2.60Gb/s

f-stack (FreeBSD + DPDK) + async-callback

1.23Gb/s

3.74Gb/s


We are trying to combine f-stack and coroutine together, so users can write more flexible code (not like the current async stype). In this situation, the latter one might drop a little bit, considering there might be the context switch overhead.

Anyway it looks like a promising results.

**Comment by beef9999** [comment]
@jfb8856606 Do you have plans to support zerocopy receive? For the 100G / 200G NICs are getting popular nowadays.
